config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# print(urlpatterns)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <title>{% block page_title %}
      
    {% endblock page_title %} | Nbnb</title>
</head>
<body class="text-gray-800 mt-24 font-light">
    {% include "partials/messages.html" %}
    <header class="container max-w-full flex inset-0 items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
        <div class="flex items-center w-1/3">
            <a href="{% url 'core:home'%}" class="mr-6">
                <img class="w-8" src="{% static 'img/logo.png'%}" alt="">
            </a>
            {% block search-bar %}
            <form method="get" action="{% url 'rooms:search'%}" class="w-9/12">
                <input class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none" name="city" placeholder="Search by City"/>
            </form>
            {% endblock search-bar %}
        </div>
        {% include "partials/nav.html" %}
        
    </header>
    {% block content %}
<<<<<<< HEAD
      <!-- 이렇게 함으로써 하위 include하는 html파일이 해당 block에 내용을 채워넣을 수 있음 -->
=======
      
>>>>>>> 2990967d0101ac83c494723e36ca69b8a4824068
    {% endblock content %}

    
    {% include "partials/footer.html" %}
</body>
</html>

templates/home_old.html
{% block page_name %}
    Home
{% endblock page_name %}
    

{% block content %}
    
    <!-- {% for room in page %} -->
    {% for room in page.object_list %}
        <h1>{{room.name}} / ${{room.price}}</h1>
    {% endfor %}

    Page {{page}} of {{page_count}}

    <h5>
        <!-- https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#ref-templates-builtins-filters -->
        <!-- {% if page != 1 %}
            <a href="?page={{page|add:-1}}">Previous</a>
        {% endif %} -->
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>

        {% endif %}



        <!-- Page {{page}} of {{page_count}} -->
        Page {{page.number}} of {{page.paginator.num_page}}

        <!-- {% if page != page_count %}
            <a href="?page={{page|add:1}}">Next</a>

        {% endif %} -->
        
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a>

        {% endif %}
            

            
        <!-- {% for page in page.paginator.page_range  %}
            {{page}}
          
        {% endfor %} -->
    </h5>

{% endblock content %}
    